### ISSUE TITLE
Async?

### ISSUE THREAD

**Issue by jamen** [Rich-Harris/tape-modern#1]
Hello @Rich-Harris!

I tried using this package, but because it's missing `t.plan` or `t.end`, I don't think it's possible to test async stuff like it claims.

Here is the situation:

1. Testing a HTTP request library.  Creates a dummy server that receives a request from the library, and sends a dummy response.
2. I write assertions in both the dummy server and dummy response.  These are asynchronous areas.
3. When running the test, it exits without doing any assertions.  I assume because it doesn't know how many assertions to expect ahead of time (purpose of `t.plan`) and there is no mechanism to tell it when to end (purpose of `t.end`)

It was easy to swap in regular `tape`.  But I'm curious, am I using the package wrong or does the package have faulty design?

**Comment by Rich-Harris** [comment]
`t.plan` and `t.end` are vestiges of Node's awkward callback-first history. Just return a promise — or, better, an `async` function:

```js
test('receives a 200 response', async t => {
  const r = await request(url);
  t.equal(r.status, 200);
});
```

**Comment by styfle** [comment]
I think you're missing `await`.

```ts
test('receives a 200 response', async t => {
  const r = await request(url);
  t.equal(r.status, 200);
});
```

**Comment by Rich-Harris** [comment]
@styfle yep, you're right — updated my comment. thanks!

**Comment by styfle** [comment]
@Rich-Harris Nice, I deleted my comment since its irrelevant now 👍
